// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_durar_10_segundos = "CgkI_bPmltAREAIQAw"; // <GPGSID>
        public const string achievement_llegar_a_los_2_minutos_todo_un_tryhard = "CgkI_bPmltAREAIQBg"; // <GPGSID>
        public const string achievement_llegar_a_los_60_segundos = "CgkI_bPmltAREAIQBQ"; // <GPGSID>
        public const string achievement_darle_a_play = "CgkI_bPmltAREAIQAg"; // <GPGSID>
        public const string achievement_llegar_a_20_segundos = "CgkI_bPmltAREAIQBA"; // <GPGSID>
        public const string achievement_abrir_el_juego = "CgkI_bPmltAREAIQAQ"; // <GPGSID>
        public const string leaderboard_score_table = "CgkI_bPmltAREAIQCA"; // <GPGSID>

}

